env:
  AUDIT_LOG_DIR: /dev/stdout
  LOG_LEVEL: info
  MAX_HEAP_MB: 200
hooks:
  migration:
    command: |
      cd /home/node/app/services/configuration-backend/prisma; npx prisma migrate deploy;
    enabled: true
replicaCount: 1
resources:
  limits:
    cpu: 100m
    memory: 350Mi
  requests:
    cpu: 100m
    memory: 300Mi
routes:
  gateway:
    namespace: unique
  pathPrefix: /configuration
  paths:
    default:
      enabled: true
    probe:
      enabled: true
service:
  port: 8095
