name: '[tf] Lint & Secure ü§®'
on:
  pull_request:
    paths:
      - governance/**/*.tf"
      - infrastructure/**/*.tf"
      - .github/workflows/tf.validate.yaml
      - .github/configs/**
      - scripts/**

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write  # Required for uploading SARIF results
    steps:

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
        with:
          fetch-depth: 0

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd #v3.1.2
        with:
          terraform_version: 1.12.0

# TODO: to be cleaned up at later point in time
      # - name: Format & Docs
      #   run: |
      #     ./scripts/tf-docs.sh
      #     ./scripts/tf-fmt.sh
      #     if [[ $(git diff --stat) != '' ]]; then
      #       echo -e '\033[0;31mDocumentation outdated or terraform not formatted, pre-commit hook was not installed or skipped!\033[0m ‚ùå'
      #       git diff --color
      #       exit 1
      #     else
      #       echo -e '\033[0;32mDocumentation and Format up to date\033[0m ‚úî'
      #     fi

      # - name: Sec
      #   run: ./scripts/tf-sec.sh

      # - name: Upload SARIF results
      #   uses: github/codeql-action/upload-sarif@6bb031afdd8eb862ea3fc1848194185e076637e5 #v3.28.11
      #   if: always()
      #   with:
      #     sarif_file: tfsec-results.sarif
